config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
                                    omniauth_callbacks: "users/omniauth_callbacks",
                                    registrations: "users/registrations"}
  root "posts#index"
  get  "/home", to: "static_pages#home"
  get  "/about", to: "static_pages#about"
  resources :users do
    member do
      get :following, :followers, :likes, :liked, :notifications, :dm
      put :notification_check
    end
  end
  resources :posts, only: %i(index new create show destroy) do
    resources :photos, only: %i(create)
    resources :likes, only: %i(create destroy), shallow: true
    resources :comments, only: %i(create destroy), shallow: true
  end
  resources :relationships, only: %i(create destroy)
  resources :direct_messages, only: %i(create)
  resources :direct_message_spaces, only: %i(create show)
  resources :hashtags, param: :hashname, only: %i(index show)
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @user = User.new
  end

    def about
    end
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>利用規約</h1> 

app/views/static_pages/home.html.erb
  
<% provide(:title, "Home") %>
<div class="main">
  <div class="container">
    <div class="mx-auto">
      <div class="form-wrap">
        <div class="form-group text-center">
          <h2 class="logo-img mx-auto"></h2>
          <h3 class="form-sub-color">写真を共有できるSNSです</h3>
          <h4><%= link_to "このアプリについて詳しく", about_path %></h4>
        </div>
      </div>
      <div class="mx-auto offset-lg-4 offset-md-3 offset-sm-2 col-lg-4 col-md-6 col-sm-8">
        <div class="form-wrap">
          <%= link_to "ログイン画面へ", new_user_session_path, class:"btn btn-primary w-100"%>
          <%= link_to "アカウントの登録画面へ", new_user_registration_path, class:"btn btn-info w-100 mt-3"%>
          <br>
          <%= form_for(@user, url: session_path(:user)) do |f| %>
            <%= f.hidden_field :email, value: 'test@example.com' %>
            <%= f.hidden_field :password, value: '123456' %>
            <%= f.submit "テストユーザーでログイン", class:"btn btn-success mt-3 w-100"%>
          <% end %>
          <span>※テストユーザの削除・編集は不可</span>
          <%= link_to "Facebookでログイン", omniauth_authorize_path(:user, :facebook), class:"btn btn-primary mt-3 w-100" %>
        </div>
      </div>
    </div>
  </div>
</div>