config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
                                    omniauth_callbacks: "users/omniauth_callbacks",
                                    registrations: "users/registrations"}
  root "posts#index"
  get  "/home", to: "static_pages#home"
  get  "/about", to: "static_pages#about"
  resources :users do
    member do
      get :following, :followers, :likes, :liked, :notifications, :dm
      put :notification_check
    end
  end
  resources :posts, only: %i(index new create show destroy) do
    resources :photos, only: %i(create)
    resources :likes, only: %i(create destroy), shallow: true
    resources :comments, only: %i(create destroy), shallow: true
  end
  resources :relationships, only: %i(create destroy)
  resources :direct_messages, only: %i(create)
  resources :direct_message_spaces, only: %i(create show)
  resources :hashtags, param: :hashname, only: %i(index show)
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships,  class_name:  "Relationship",
                                   foreign_key: "follower_id",
                                   dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :direct_messages, dependent: :destroy
  has_many :direct_message_space_users, dependent: :destroy
  has_many :notifications, foreign_key: "to_user_id", dependent: :destroy
  has_many :notifications, foreign_key: "from_user_id", dependent: :destroy
  has_many :users
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable
  validates :name,      presence: true, length: { maximum: 50 }
  validates :user_name, presence: true, length: { maximum: 50 }
  mount_uploader :profile_photo, ProfilePhotoUploader

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    user ||= User.create(
      uid:            auth.uid,
      provider:       auth.provider,
      name:           auth.info.name,
      user_name:      auth.info.name,
      email:          User.dummy_email(auth),
      remote_profile_photo_url:  auth.info.image,
      password:       Devise.friendly_token[0, 20]
    )
    user
  end

  def self.search(search)
    if search
      where(["user_name LIKE ?", "%#{search}%"])
    else
      all
    end
  end

  def feed
    Post.where("user_id IN (:following_ids)", following_ids: following_ids)
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_from :facebook
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :authenticate_test_user, only: [:edit, :destroy]

  def authenticate_test_user
    if current_user == User.find(1)
      redirect_to root_path
    end
  end

  protected

  def update_resource(resource, params)
    return super if params["password"]
    resource.update_without_password(params.except("current_password"))
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: %i(show following followers)
  
    def index
      @users = User.all.page(params[:page]).per(USER_PER)
    end
  
    def show
      @posts = Post.where(user_id: @user.id).order("created_at DESC").page(params[:page]).per(USER_PER)
    end
  
    def following
    end
  
    def followers
    end
  
    def likes
      @user = User.includes(posts: [:likes, :photos]).find(params[:id])
      posts = Post.find(Like.where(user_id: @user.id).order("created_at DESC").pluck(:post_id))
      @posts = Kaminari.paginate_array(posts).page(params[:page]).per(POST_PER)
    end
  
    def liked
      @user = User.includes(posts: [:likes, :photos]).find(params[:id])
      posts = Post.where(user_id: @user.id).order("created_at DESC").to_a.select { |post| post.likes != [] }
      @posts = Kaminari.paginate_array(posts).page(params[:page]).per(POST_PER)
    end
  
    def notifications
      @notifications = Notification.where(to_user_id: current_user.id).order("created_at DESC").page(params[:page]).per(INDEX_PER)
    end
  
    def notification_check
      Notification.where(to_user_id: current_user.id, checked: false).update_all(checked: true)
      redirect_to notifications_user_path(current_user)
    end
  
    def dm
      current_user_dm_spaces = DirectMessageSpaceUser.where(user_id: current_user.id).map(&:direct_message_space)
      @dm_spaces = DirectMessageSpaceUser.where(direct_message_space: current_user_dm_spaces).
        where.not(user_id: current_user.id).map(&:direct_message_space)
      dm_users_id = DirectMessageSpaceUser.where(direct_message_space: @dm_spaces).where.not(user_id: current_user.id).map(&:user_id)
      @dm_users = User.where(id: dm_users_id)
      @dm_unchecked_counts = []
      @dm_spaces.zip(@dm_users).each do |dm_space, dm_user|
        @dm_unchecked_counts << DirectMessage.where(direct_message_space_id: dm_space.id, user_id: dm_user.id, checked: false).count
      end
    end
  
    private
  
    def set_user
      @user = User.find(params[:id])
    end
  end

app/views/users/_login_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">設定</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="list-group text-center">
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "list-group-item list-group-item-action" %>
        <%= link_to "キャンセル", "#", class: "list-group-item list-group-item-action", "data-dismiss": "modal" %>
      </div>
    </div>
  </div>
</div>

app/views/users/_user_index.html.erb
<div class="container">
  <div class="row">
    <% users.each do |user| %>
      <div class="col-4 col-sm-4 col-md-4">
        <div class="card">
          <a data-toggle="modal" data-target="#photo-<%= user.id %>" class="modal-open">
            <%= image_tag avatar_url(user), class: "card-img-top" %>
          </a>
          <%= render "partial/user_modal", user: user %>
          <div class="card-body text-center">
            <h5 class="card-title"><%= user.user_name%></h5>
            <p class="card-text"><%= user.bio %></p>
            <%= render "partial/follow_form", user: user %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/dm.html.erb
<% provide(:title, "dm") %>
<div class="container text-center">
  <h3>DM一覧</h3>
  <% if @dm_spaces %>
    <% @dm_spaces.zip(@dm_users, @dm_unchecked_counts).each do |dm_space, dm_user, dm_unchecked_count| %>
      <div class="userBox">
        <div class="row">
          <div class="offset-md-1 col-md-1 d-flex align-items-center">
            <%= dm_user.user_name %>
          </div>
          <div class="col-md-1 d-flex align-items-center">
            <%= link_to dm_user do %>
              <figure>
                <%= image_tag avatar_url(dm_user), class: "post-profile-icon m-3" %>
              </figure>
            <% end %>
          </div>
          <div class="col-md-5 d-flex align-items-center">
            <% if dm_space.direct_messages.last %>
              <span class="mr-3">
                <%= "#{dm_space.direct_messages.last.user.user_name}:" %>
              </span>
              <%= link_to direct_message_space_path(dm_space) do %>
                <%= "#{dm_space.direct_messages.last.message}" %>
              <% end%>
            <% end %>
          </div>
          <div class="col-md-2 d-flex align-items-center">
            <% if dm_space.direct_messages.last %>
              <%= time_ago_in_words(dm_space.direct_messages.last.created_at).upcase%>前
            <% end %>
          </div>
          <div class="col-md-2 d-flex align-items-center">
            <% if dm_unchecked_count > 0 %>
              <span class="badge badge-danger"><%= dm_unchecked_count %></span>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/followers.html.erb
<% provide(:title, 'followers') %>
<div class="container">
  <div class="btn-group d-flex" role="group">
    <%= link_to "following", following_user_path(params[:id]),class: "btn btn-dafault w-100" %>
    <%= link_to "followers", followers_user_path(params[:id]),class: "btn btn-primary w-100" %>
  </div>
  <%= render "user_index", users: @user.followers %>
</div>

app/views/users/following.html.erb
<% provide(:title, 'following') %>
<div class="container">
  <div class="btn-group d-flex" role="group">
    <%= link_to "following", following_user_path(params[:id]),class: "btn btn-primary w-100" %>
    <%= link_to "followers", followers_user_path(params[:id]),class: "btn btn-default w-100" %>
  </div>
  <%= render "user_index", users: @user.following %>
</div>

app/views/users/index.html.erb
<% provide(:title, "All users") %>
<%= render "users/user_index", users: @users  %>
<%= paginate(@users) %>

app/views/users/liked.html.erb
<% provide(:title, "liked") %>
<div class="container">
  <div class="btn-group d-flex" role="group">
    <%= link_to "いいねした投稿", likes_user_path(params[:id]),class: "btn btn-default w-100" %>
    <%= link_to "いいねされた投稿", liked_user_path(params[:id]),class: "btn btn-primary w-100" %>
  </div>
  <%= render "partial/photos_index", posts: @posts%>
</div>

app/views/users/likes.html.erb
<% provide(:title, "likes") %>
<div class="container">
  <div class="btn-group d-flex" role="group">
    <%= link_to "いいねした投稿", likes_user_path(params[:id]),class: "btn btn-primary w-100" %>
    <%= link_to "いいねされた投稿", liked_user_path(params[:id]),class: "btn btn-default w-100" %>
  </div>
  <%= render "partial/photos_index", posts: @posts%>
</div>

app/views/users/notifications.html.erb
<% provide(:title, "notification") %>
<div class="container text-center">
  <h3>通知</h3>
  <%= link_to "全て既読にする", notification_check_user_path, method: :put %>
  <% @notifications.each do |notification| %>
    <% if notification %>
      <div class="userBox">
        <div class="row">
          <div class="offset-md-1 col-md-1 d-flex align-items-center">
            <%= notification.from_user.user_name %>
          </div>
          <div class="col-md-1 d-flex align-items-center">
            <%= link_to notification.from_user do %>
              <figure>
                <%= image_tag avatar_url(notification.from_user), class: "post-profile-icon m-3" %>
              </figure>
            <% end %>
          </div>
          <div class="col-md-5 d-flex align-items-center">
            <% if notification.direct_message %>
              <%= link_to direct_message_space_path(notification.direct_message.direct_message_space) do %>
                <%= "#{notification.from_user.user_name}からダイレクトメッセージが届いています" %>
              <% end %>
            <% end %>
            <% if notification.like %>
              <%= link_to post_path(notification.like.post) do %>
                <%= "#{notification.from_user.user_name}からいいねが届いています" %>
              <% end %>
            <% end %>
            <% if notification.comment %>
              <%= link_to post_path(notification.comment.post) do %>
                <%= "#{notification.from_user.user_name}からコメントが届いています" %>
              <% end %>
              <%= "　#{notification.from_user.user_name}：#{notification.comment.comment}" %>
            <% end %>
            <% if notification.relationship %>
              <%= link_to user_path(notification.from_user) do %>
                <%= "#{notification.from_user.user_name}からフォローされました" %>
              <% end %>
            <% end %>
          </div>
          <div class="col-md-2 d-flex align-items-center">
            <%= time_ago_in_words(notification.created_at).upcase%>前
          </div>
          <div class="col-md-2 d-flex align-items-center">
            <% unless notification.checked %>
              <span class="badge badge-danger">N</span>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
  <div class="offset-md-4">
    <%= paginate @notifications %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "User" + @user.id.to_s) %>
<div class="container">
  <div class="profile-wrap">
    <div class="row">
      <div class="col-md-4 text-center">
        <%= image_tag avatar_url(@user), class: "round-img" %>
      </div>
      <div class="col-md-8">
        <div class="row">
          <h1><%= @user.user_name %></h1>
          <% if @user == current_user %>
            <%= link_to "プロフィールを編集", edit_user_registration_path, class: "btn btn-outline-dark common-btn edit-profile-btn" %>
            <button type="button" class="setting" data-toggle="modal" data-target="#exampleModal"></button>
          <% end %>
          <% if user_signed_in? %>
            <%= render "partial/follow_form", user: @user %>
          <% end %>
          <% unless current_user?(@user) %>
            <%= form_tag direct_message_spaces_path, method: :post do %>
              <input name="user_id" type="hidden" value="<%= @user.id %>" />
              <%= submit_tag "DMを送る", class: "btn btn-primary common-btn edit-profile-btn" %>
            <% end %>
          <% end %>
          <%= render "login_modal" %>
        </div>
        <section class="stats">
          <%= render "partial/stats", user: @user %>
        </section>
        <p id="userName"><strong><%= @user.name %></strong></p>
        <div class="bio">
          <%= @user.bio %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <%= render "partial/photos_index", posts: @posts %>
</div>