config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
                                    omniauth_callbacks: "users/omniauth_callbacks",
                                    registrations: "users/registrations"}
  root "posts#index"
  get  "/home", to: "static_pages#home"
  get  "/about", to: "static_pages#about"
  resources :users do
    member do
      get :following, :followers, :likes, :liked, :notifications, :dm
      put :notification_check
    end
  end
  resources :posts, only: %i(index new create show destroy) do
    resources :photos, only: %i(create)
    resources :likes, only: %i(create destroy), shallow: true
    resources :comments, only: %i(create destroy), shallow: true
  end
  resources :relationships, only: %i(create destroy)
  resources :direct_messages, only: %i(create)
  resources :direct_message_spaces, only: %i(create show)
  resources :hashtags, param: :hashname, only: %i(index show)
end

app/views/partial/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, user.id %></div>
  <%= f.submit "フォローする", class: "btn btn-primary common-btn edit-profile-btn" %>
<% end %>

app/views/partial/_follow_form.html.erb
<% unless current_user?(user) %>
  <div id="follow_form-<%= user.id %>">
    <% if current_user.following?(user) %>
      <%= render "partial/unfollow", user: user %>
    <% else %>
      <%= render "partial/follow", user: user %>
    <% end %>
  </div>
<% end %>

app/views/partial/_footer.html.erb
<footer class="footer">
  <div class="container">
    <%= link_to "投稿", new_post_path, class: "btn btn-primary btn-block" %>
  </div>
</footer> 

app/views/partial/_navbar.html.erb
<nav class="navbar navbar-icon-top navbar-expand-lg navbar-light bg-light">
  <%= link_to("", root_path, class: "navbar-brand") %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to(root_path, class: "nav-link") do %>
          <i class="fa fa-home"></i>
          Timeline
        <% end %>
        <span class="sr-only">(current)</span>
      </li>
      <li class="nav-item">
        <%= link_to(notifications_user_path(current_user), class: "nav-link") do %>
          <i class="fa fa-bell">
            <% if @notification_count > 0 %>
              <span class="badge badge-info"><%= @notification_count %></span>
            <% end %>
          </i>
          通知
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to(dm_user_path(current_user), class: "nav-link") do %>
          <i class="fa fa-envelope">
            <% if @dm_count > 0 %>
              <span class="badge badge-danger"><%= @dm_count %></span>
            <% end %>
          </i>
          DM
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to(liked_user_path(current_user), class: "nav-link") do %>
        <i class="fa fa-heart"></i>
          いいね
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to(users_path, class: "nav-link") do %>
          <i class="fa fa-users"></i>
          All Users
        <% end %>
      </li>
    </ul>
    <ul class="navbar-nav ">
      <li class="nav-item">
        <%= link_to(new_post_path, class: "nav-link") do %>
          <i class="fa fa-camera"></i>
          新規投稿
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to(user_path(current_user), class: "nav-link") do %>
          <i class="fa fa-user"></i>
          User Page
        <% end %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-cog"></i>
          config
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to("User Page", user_path(current_user), class: "dropdown-item") %>
          <%= link_to("User Edit", edit_user_registration_path, class: "dropdown-item") %>
          <%= link_to("Log Out", destroy_user_session_path, method: :delete, class: "dropdown-item") %>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Cancel</a>
        </div>
      </li>
      <li class="nav-item">
        <%= link_to(about_path, class: "nav-link") do %>
          <h4>About</h4>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/partial/_photo_modal.html.erb
<div class="modal fade" id="photo-<%= post.id %>" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="row">
        <div class="mx-auto w-100">
          <div class="row post-wrap">
            <div class="col-lg-8">
              <div class="card-left">
                <div id="carousel-<%= post.id %>" class="carousel slide" data-ride="carousel">
                  <div class="carousel-inner">
                    <% post.photos.each.with_index(1) do |photo, i| %>
                      <% if i == 1 %>
                        <div class="carousel-item active">
                          <%= image_tag photo.image.url(:medium), class: "card-img-top" %>
                        </div>
                      <% else %>
                        <div class="carousel-item">
                          <%= image_tag photo.image.url(:medium), class: "card-img-top" %>
                        </div>
                        <a class="carousel-control-prev" href="#carousel-<%= post.id%>" role="button" data-slide="prev">
                          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                          <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carousel-<%= post.id%>" role="button" data-slide="next">
                          <span class="carousel-control-next-icon" aria-hidden="true"></span>
                          <span class="sr-only">Next</span>
                        </a>
                      <% end %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-lg-4">
              <div class="card-right">
                <div class="card-right-comment pr-3">
                  <div class="card-right-name d-flex">
                    <%= link_to user_path(post.user), class: "no-text-decoration" do %>
                      <%= image_tag avatar_url(post.user), class: "post-profile-icon" %>
                      <strong><%= post.user.user_name %></strong>
                    <% end %>
                    <% if post.user_id == current_user.id %>
                      <%= link_to post_path(post), method: :delete, class: "ml-auto mx-0 my-auto" do %>
                        <div class="delete-post-icon">
                        </div>
                      <% end %>
                    <% end %>
                  </div>
                  <div class="comment-post-id">
                    <div class="m-2">
                      <div id="comment-post-<%= post.id.to_s %>">
                        <%= render 'posts/comment_list', post: post %>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="row parts">
                  <div id="like-icon-post-<%= post.id.to_s %>">
                    <% if post.liked_by(current_user).present? %>
                      <%= link_to "いいねを取り消す", like_path(post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text" %>
                    <% else %>
                      <%= link_to "いいね", post_likes_path(post), method: :POST, remote: true, class: "love hide-text" %>
                    <% end %>
                  </div>
                </div>
                <div id="like-text-post-<%= post.id.to_s %>">
                  <%= render "posts/like_text", { likes: post.likes } %>
                </div>
                <div class="post-time"><%= time_ago_in_words(post.created_at).upcase %>前</div>
                <hr>
                <div class="modal-meta-bottom" id="comment-form-post-<%= post.id.to_s %>">
                  <%= form_for [post, Comment.new], html: { class: "w-100" }, remote: true do |f| %>
                    <%= f.hidden_field :user_id, value: current_user.id %>
                    <%= f.hidden_field :post_id, value: post.id %>
                    <%= f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメントを追加...", autocomplete: :off %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/partial/_photos_index.html.erb
<div class="row">
  <% if posts.any? %>
    <% posts.each do |post|%>
      <div class="col-md-4 col-sm-4 col-4">
        <div class="mb-4">
          <a data-toggle="modal" data-target="#photo-<%= post.id %>" class="modal-open">
            <% if post.photos.first %>
              <%= image_tag post.photos.first.image.url(:medium), class: "card-img-top" %>
            <% end %>
          </a>
          <%= render "partial/photo_modal", post: post %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
<div class="row">
  <div class="offset-md-5 offset-sm-5 offset-5">
    <%= paginate(@posts) %>
  </div>
</div>

app/views/partial/_stats.html.erb
<% user ||= current_user %>
<div class="stats">
  <strong id="photos" class="stat">
    <%= "投稿#{user.posts.map(&:photos).count}件" %>
  </strong>
  <%= link_to followers_user_path(user) do %>
    <strong id="followers" class="stat">
      <%= "フォロワー#{user.followers.count}人" %>
    </strong>
  <% end %>
  <%= link_to following_user_path(user) do %>
    <strong id="following" class="stat">
      <%= "#{user.following.count}人をフォロー中" %>
    </strong>
  <% end %>
</div>

app/views/partial/_unfollow.html.erb
<button type="button" class="btn　common-btn edit-profile-btn" data-toggle="modal" data-target="#unfollowModal">フォロー中</button>
<div class="modal fade" id="unfollowModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="list-group text-center">
        <%= image_tag avatar_url(user), class: "round-img mx-auto", style: "width:70px; height:70px;" %>
        <p><%= "#{user.user_name}さんのフォローをやめますか？" %></p>
        <%= form_for(current_user.active_relationships.find_by(followed_id: user.id),
                     html: { method: :delete }) do |f| %>
          <%= f.submit "フォローをやめる", class: "list-group-item list-group-item-action" %>
        <% end %>
        <%= link_to "キャンセル", "#", class: "list-group-item list-group-item-action", "data-dismiss": "modal" %>
      </div>
    </div>
  </div>
</div>

app/views/partial/_user_modal.html.erb
<div class="modal fade" id="photo-<%= user.id %>" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="container">
        <div class="profile-wrap">
          <div class="row">
            <div class="col-md-4 text-center">
              <%= link_to user_path(user) do %>
                <%= image_tag avatar_url(user), class: "round-img" %>
              <% end %>
            </div>
            <div class="col-md-8">
              <div class="row">
                <%= link_to user_path(user) do %>
                  <h1><%= user.user_name %></h1>
                <% end %>
                <% if user == current_user %>
                  <%= link_to "プロフィールを編集", edit_user_registration_path, class: "btn btn-outline-dark common-btn edit-profile-btn" %>
                  <button type="button" class="setting" data-toggle="modal" data-target="#exampleModal"></button>
                <% end %>
                <% if user_signed_in? %>
                  <%#= render "partial/follow_form", user: user %>
                <% end %>
                <% unless current_user?(user) %>
                  <%= form_tag direct_message_spaces_path, method: :post do %>
                    <input name="user_id" type="hidden" value="<%= user.id %>" />
                    <%= submit_tag "DMを送る", class: "btn btn-primary common-btn edit-profile-btn" %>
                  <% end %>
                <% end %>
                <%= render "users/login_modal", user: user %>
              </div>
              <section class="stats">
                <%= render "partial/stats", user: user %>
              </section>
              <p id="userName"><strong><%= user.name %></strong></p>
              <div class="bio">
                <%= user.bio %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="container">
        <div id="carousel-<%= user.id %>" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <% user.posts.each.with_index(1) do |post, i| %>
              <% if i == 1%>
                <div class="carousel-item active">
                  <div class="comment-img">
                    <%= image_tag avatar_url(post.user), class: "post-profile-icon" %>
                    <strong><%= post.user.user_name %></strong>
                    <span><%= render_by_hashtag(post.title) %></span>
                    <span class="date sub-text"><%= time_ago_in_words(post.created_at).upcase %>前</span>
                  </div>
                  <% if post.photos.first %>
                    <%= image_tag post.photos.first.image.url(:medium), class: "card-img-top" %>
                  <% end %>
                </div>
              <% else %>
                <div class="carousel-item">
                  <div class="comment-img">
                    <%= image_tag avatar_url(post.user), class: "post-profile-icon" %>
                    <strong><%= post.user.user_name %></strong>
                    <span><%= render_by_hashtag(post.title) %></span>
                    <span class="date sub-text"><%= time_ago_in_words(post.created_at).upcase %>前</span>
                  </div>
                  <% if post.photos.first%>
                    <%= image_tag post.photos.first.image.url(:medium), class: "card-img-top" %>
                  <% end %>
                </div>
                <a class="carousel-control-prev" href="#carousel-<%= user.id%>" role="button" data-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carousel-<%= user.id%>" role="button" data-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="sr-only">Next</span>
                </a>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>