config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
                                    omniauth_callbacks: "users/omniauth_callbacks",
                                    registrations: "users/registrations"}
  root "posts#index"
  get  "/home", to: "static_pages#home"
  get  "/about", to: "static_pages#about"
  resources :users do
    member do
      get :following, :followers, :likes, :liked, :notifications, :dm
      put :notification_check
    end
  end
  resources :posts, only: %i(index new create show destroy) do
    resources :photos, only: %i(create)
    resources :likes, only: %i(create destroy), shallow: true
    resources :comments, only: %i(create destroy), shallow: true
  end
  resources :relationships, only: %i(create destroy)
  resources :direct_messages, only: %i(create)
  resources :direct_message_spaces, only: %i(create show)
  resources :hashtags, param: :hashname, only: %i(index show)
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :photos, dependent: :destroy
    has_many :likes, -> { order(created_at: :desc) }, dependent: :destroy
    has_many :comments, -> { order(created_at: :desc) }, dependent: :destroy
    has_many :hashtag_posts, dependent: :destroy
    has_many :hashtags, through: :hashtag_posts
    validates :photos, associated: true
    mount_uploader :image, PhotoUploader

    after_create do
      post = Post.find_by(id: id)
      if post.title
        hashtags = title.scan(/[#＃][^#＃\p{blank}]+/)
        hashtags.uniq.map do |hashtag|
          tag = Hashtag.find_or_create_by(hashname: hashtag.slice(1..-1)) # 先頭の"#"は除いて保存
          post.hashtags << tag
        end
      end
    end
  
    def liked_by(user)
      Like.find_by(user_id: user.id, post_id: id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i(index)
  before_action :set_post, only: %i(show destroy)

  def index
    if user_signed_in?
      @posts = current_user.feed.includes(:photos, :user, :likes).order("created_at DESC").page(params[:page]).per(POST_PER)
    else
      redirect_to home_path
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if params[:images]
      params[:images].each do |img|
        @post.save
        @post.photos.create(image: img)
      end
      redirect_to root_path
      flash[:notice] = "投稿が保存されました"
    else
      redirect_to root_path
      flash[:alert] = "投稿に失敗しました"
    end
  end

  def show
    @photos = @post.photos
    @likes = @post.likes.includes(:user)
  end

  def destroy
    if @post.user == current_user
      flash[:notice] = "投稿が削除されました" if @post.destroy
    else
      flash[:alert] = "投稿の削除に失敗しました"
    end
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:caption).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find_by(id: params[:id])
  end
end

app/views/posts/_comment_list.html.erb
<ul class="img-comment-list">
  <li>
    <div class="comment-img">
      <%= image_tag avatar_url(post.user), class: "post-profile-icon" %>
    </div>
    <div class="comment-text">
      <strong><%= post.user.user_name %></strong>
     <span class="date sub-text"><%= time_ago_in_words(post.created_at).upcase %>前</span>
    </div>
  </li>
  <% post.comments.reverse.each do |comment| %>
    <li>
      <% if comment.user == current_user %>
        <%= link_to "", comment_path(comment), method: :delete, remote: true, class: "delete-comment" %>
      <% end %>
      <div class="comment-img">
        <%= image_tag avatar_url(comment.user), class: "post-profile-icon" %>
      </div>
      <div class="comment-text">
        <strong><%= link_to comment.user.user_name, user_path(comment.user)%></strong>
        <p><%= comment.comment %></p> <span class="date sub-text"><%= time_ago_in_words(comment.created_at).upcase %>前</span>
      </div>
    </li>
  <% end %>
</ul>

app/views/posts/_like_text.html.erb
<% if likes.size > 0 %>
  <strong>いいね！<%= likes.size %>件</strong>
<% end %>

app/views/posts/index.html.erb
<% provide(:title, "Timeline") %>
<h3 class="text-center">TimeLine</h3>
<div class="container">
  <%= render "partial/photos_index", posts: @posts %>
</div>

app/views/posts/new.html.erb
<% provide(:title, "Post") %>
<div class="d-flex flex-column align-items-center mt-3">
  <div class="col-xl-7 col-lg-8 col-md-10 col-sm-11 post-card">
    <div class="card">
      <div class="card-header">
        投稿画面
      </div>
      <div class="card-body">
        <%= form_for @post, html: { multipart: true, class: "upload-images p-0 border-0" } do |f| %>
          <div class="form-group row mt-2">
            <div class="col-auto pr-0">
              <%= image_tag avatar_url(current_user), class: "post-profile-icon" %>
            </div>
            <div class="col pl-0">
              <%= f.text_field :title, class: "form-control border-0", placeholder: "コメントを書く(＃〜でハッシュタグ)" %>
            </div>
          </div>
          <div class="mb-3">
            <span>画像(複数選択可)</span>
            <%= file_field_tag "images[]", type: :file, multiple: true %>
          </div>
          <%= f.submit "投稿する", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<% provide(:title, "post" + @post.id.to_s) %>
<div class="col-md-10 col-md-offset-1 mx-auto postShow-wrap">
  <div class="row post-wrap">
    <div class="col-md-8">
      <div class="card-left">
        <%= image_tag @post.photos.first.image.url(:medium), class: "card-img-top" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card-right">
        <div class="card-right-comment">
          <div class="card-right-name d-flex">
            <%= link_to user_path(@post.user), class: "no-text-decoration" do %>
              <%= image_tag avatar_url(@post.user), class: "post-profile-icon" %>
            <% end %>
            <%= link_to user_path(@post.user), class: "black-color no-text-decoration",
              title: @post.user.user_name do %>
              <strong><%= @post.user.user_name %></strong>
            <% end %>

            <% if @post.user_id == current_user.id %>
              <%= link_to post_path(@post), method: :delete, class: "ml-auto mx-0 my-auto" do %>
                <div class="delete-post-icon">
                </div>
              <% end %>
            <% end %>
          </div>
          <div class="m-2">
            <strong>
              <%= @post.title %>
          </div>
          <div class="comment-post-id">
            <div class="m-2">
              <div id="comment-post-<%= @post.id.to_s %>">
                <%= render 'comment_list', post: @post %>
              </div>
            </div>
          </div>
        </div>
        <div class="row parts">
          <div id="like-icon-post-<%= @post.id.to_s %>">
            <% if @post.liked_by(current_user).present? %>
              <%= link_to "いいねを取り消す", like_path(@post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text" %>
            <% else %>
              <%= link_to "いいね", post_likes_path(@post), method: :POST, remote: true, class: "love hide-text" %>
            <% end %>
          </div>
        </div>
        <div id="like-text-post-<%= @post.id.to_s %>">
          <%= render "like_text", { likes: @likes } %>
        </div>
        <div class="post-time"><%= time_ago_in_words(@post.created_at).upcase %>前</div>
        <hr>
        <div class="row parts" id="comment-form-post-<%= @post.id.to_s %>">
          <%= form_for [@post, Comment.new], html: { class: "w-100" }, remote: true do |f| %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <%= f.hidden_field :post_id, value: @post.id %>
            <%= f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメントを追加...", autocomplete: :off %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>